"""Foundational unit tests for SCRUM Poker ORM models.

Covers model instantiation, defaults, field constraints, and inter-model
relationships using an in-memory SQLite database via the db_session fixture.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

import pytest

from app.models.configuration import Configuration
from app.models.participant import Participant
from app.models.session import Session as PokerSession
from app.models.storage_issue import StorageIssue
from app.models.team import Team
from app.models.vote import VALID_CARD_VALUES, Vote


# ── Team ──────────────────────────────────────────────────────────────────────


class TestTeamModel:
    """Tests for the Team ORM model."""

    def test_team_defaults_created_at(self, db_session):
        """Team.created_at is populated automatically when not supplied."""
        team = Team(name="Alpha Squad")
        db_session.add(team)
        db_session.flush()
        assert team.created_at is not None

    def test_team_id_is_uuid(self, db_session):
        """Team.id is a UUID v4 generated by default."""
        team = Team(name="Beta Team")
        db_session.add(team)
        db_session.flush()
        assert isinstance(team.id, uuid.UUID)

    def test_team_name_is_stored(self, db_session):
        """Team.name round-trips through the session correctly."""
        team = Team(name="Gamma Crew")
        db_session.add(team)
        db_session.flush()
        fetched = db_session.get(Team, team.id)
        assert fetched is not None
        assert fetched.name == "Gamma Crew"


# ── Configuration ─────────────────────────────────────────────────────────────


class TestConfigurationModel:
    """Tests for the Configuration singleton ORM model."""

    def test_configuration_singleton_id(self, db_session):
        """Configuration row is created with id=1."""
        config = Configuration(id=1, updated_at=datetime.now(timezone.utc))
        db_session.add(config)
        db_session.flush()
        assert config.id == 1

    def test_configuration_nullable_fields(self, db_session):
        """base_url_for_issues and default_theme default to None."""
        config = Configuration(id=1, updated_at=datetime.now(timezone.utc))
        db_session.add(config)
        db_session.flush()
        assert config.base_url_for_issues is None
        assert config.default_theme is None

    def test_configuration_base_url_stored(self, db_session):
        """base_url_for_issues round-trips correctly."""
        config = Configuration(
            id=1,
            base_url_for_issues="https://jira.example.com/browse",
            updated_at=datetime.now(timezone.utc),
        )
        db_session.add(config)
        db_session.flush()
        fetched = db_session.get(Configuration, 1)
        assert fetched is not None
        assert fetched.base_url_for_issues == "https://jira.example.com/browse"


# ── Session ───────────────────────────────────────────────────────────────────


class TestSessionModel:
    """Tests for the Session ORM model."""

    def _make_team(self, db_session, name: str = "Ops") -> Team:
        t = Team(name=name)
        db_session.add(t)
        db_session.flush()
        return t

    def test_session_defaults(self, db_session):
        """Session.status defaults to 'active' and card_set_name to fibonacci."""
        team = self._make_team(db_session)
        session = PokerSession(name="Sprint 1", team_id=team.id, sprint_number=1)
        db_session.add(session)
        db_session.flush()
        assert session.status == "active"
        assert session.card_set_name == "fibonacci_plus_specials"
        assert session.completed_at is None

    def test_session_id_is_uuid(self, db_session):
        """Session.id is auto-generated UUID."""
        team = self._make_team(db_session, "DevOps")
        s = PokerSession(name="Meeting", team_id=team.id, sprint_number=2)
        db_session.add(s)
        db_session.flush()
        assert isinstance(s.id, uuid.UUID)

    def test_session_created_at_auto(self, db_session):
        """Session.created_at is set on flush."""
        team = self._make_team(db_session, "QA")
        s = PokerSession(name="QA Sprint", team_id=team.id, sprint_number=3)
        db_session.add(s)
        db_session.flush()
        assert s.created_at is not None


# ── StorageIssue ──────────────────────────────────────────────────────────────


class TestStorageIssueModel:
    """Tests for the StorageIssue ORM model."""

    def _make_session(self, db_session) -> PokerSession:
        team = Team(name="IssueTeam")
        db_session.add(team)
        db_session.flush()
        s = PokerSession(name="Issue Test", team_id=team.id, sprint_number=1)
        db_session.add(s)
        db_session.flush()
        return s

    def test_issue_defaults(self, db_session):
        """StorageIssue.is_active defaults to False and revealed_at to None."""
        s = self._make_session(db_session)
        issue = StorageIssue(
            session_id=s.id,
            issue_type="Story",
            issue_key="PROJ-1",
            summary="As a user I want things",
        )
        db_session.add(issue)
        db_session.flush()
        assert issue.is_active is False
        assert issue.revealed_at is None
        assert issue.final_estimate is None

    def test_issue_type_story_and_bug(self, db_session):
        """Both 'Story' and 'Bug' issue types are accepted."""
        s = self._make_session(db_session)
        story = StorageIssue(
            session_id=s.id, issue_type="Story", issue_key="S-1", summary="Story"
        )
        bug = StorageIssue(
            session_id=s.id, issue_type="Bug", issue_key="B-1", summary="Bug"
        )
        db_session.add_all([story, bug])
        db_session.flush()
        assert story.issue_type == "Story"
        assert bug.issue_type == "Bug"


# ── Vote ──────────────────────────────────────────────────────────────────────


class TestVoteModel:
    """Tests for the Vote ORM model."""

    def test_valid_card_values_constant(self):
        """VALID_CARD_VALUES contains the expected card set."""
        expected = {"1", "2", "3", "5", "8", "13", "?", "☕", "♾"}
        assert VALID_CARD_VALUES == expected

    def test_vote_timestamps_auto(self, db_session):
        """Vote.created_at and updated_at are set on flush."""
        team = Team(name="VoteTeam")
        db_session.add(team)
        db_session.flush()
        session = PokerSession(name="VS", team_id=team.id, sprint_number=1)
        db_session.add(session)
        db_session.flush()
        issue = StorageIssue(
            session_id=session.id,
            issue_type="Story",
            issue_key="V-1",
            summary="Vote story",
        )
        db_session.add(issue)
        db_session.flush()
        participant = Participant(
            session_id=session.id, user_identifier="user-1"
        )
        db_session.add(participant)
        db_session.flush()
        vote = Vote(
            issue_id=issue.id,
            participant_id=participant.id,
            card_value="5",
        )
        db_session.add(vote)
        db_session.flush()
        assert vote.created_at is not None
        assert vote.updated_at is not None


# ── Participant ───────────────────────────────────────────────────────────────


class TestParticipantModel:
    """Tests for the Participant ORM model."""

    def test_participant_defaults(self, db_session):
        """Participant.is_leader defaults to False."""
        team = Team(name="ParticipantTeam")
        db_session.add(team)
        db_session.flush()
        session = PokerSession(name="PS", team_id=team.id, sprint_number=1)
        db_session.add(session)
        db_session.flush()
        p = Participant(session_id=session.id, user_identifier="alice")
        db_session.add(p)
        db_session.flush()
        assert p.is_leader is False
        assert p.left_at is None
        assert p.active_issue_id is None
